### ISSUE TITLE
FOIL generator

### ISSUE THREAD

**Issue by ebrelsford** [nycommons/nycommons-django#4]
This will allow visitors to any property's page a straightforward way to email a FOIL (freedom of information law) request to the appropriate agency.

## UI

Each property's page will have a button (after "Why is this property part of NYCommons?") that reads "Request Agency Documents". Under the button should be this text:

> The agency has to share most documents it has about this property under the New York State Freedom of Information Law. Click to send them a request!

## Functionality

The button will ideally be a `mailto` link that creates the following email in the clicker's mail client:

```
To: [INSERT FOIL OFFICER EMAIL FROM TABLE]
Bcc: [an NYCommons email address]
Subject: FOIL Request: [Borough] Block [#] Lot [#]

Dear FOIL Officer, 

Please treat this request for all documents in your Agency’s possession related to [Borough] 
Block [#] Lot [#] as a request under the New York State Freedom of Information Law. 

Please send electronic copies of all documents to this email address.

I look forward to hearing from you within five days as required by law.

Best, 

ADD YOUR NAME HERE. YOU CAN ALSO ADD MORE DETAILS ABOUT THE DOCUMENTS YOU 
ARE LOOKING FOR TO THE LETTER ABOVE. REMEMBER TO DELETE THIS LINE BEFORE YOU 
SEND!
```

## Future improvements

This is out of scope for this phase of work, but down the line we would like to be able to automatically follow up with people who have sent FOIL requests. This would require us asking the sender for their email address and tracking the FOIL request.

Can we use [the MuckRock API](https://www.muckrock.com/api/) for any of this, such as [agency details](https://www.muckrock.com/api_v1/agency/?name=&status=approved&jurisdiction=17&types=)?

## Tasks
 * [x] investigate whether a `mailto` link can be this long in the first place
 * [x] load FOIL contacts table as an entity in Django that can be used to look up email/name by agency
 * [x] expose contacts table to admin site in Django so users can add to / correct them
 * [x] add button to each property's page with appropriate link
 * [ ] track clicks on the button as [an event in our analytics platform, Piwik](https://piwik.org/docs/event-tracking/)

**Comment by ebrelsford** [comment]
For now we're going to have the email BCC Paula (will provide the email address separately).
